dist: trusty
language: java
jdk:
- oraclejdk8
install:
- mvn clean test
deploy:
  provider: script
  script: mvn deploy -s deploy.settings.xml -Dmaven.test.skip=true -DdeployAtEnd=true
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: U/fHP5R/OuQ1fQCGd+uk7hTI/YSrtcG61yzg5MT6c+MoPiVScLeiLZv4uLZ/6ZpmrSt22LvgxNQv79UtQAxpF47D7MuDLnXHScnjqCCkKGgxr1MSaD0s4+y6nVOXDVGKCWJzOYWJnYxhChY6dbjjRdKQgyNI2BfOWcHn8tKGWs0=
  - secure: cPf68inCG+pnmYpZk5QoqVjeMSdrEUlr5INlqQgbB8FxAd29pdJ5E2M+6xHTfnr7EVRXp/JUaFXwPOoAFaKL6OSlbpZT9LOkwQWHbi9sJ8gJOB58Rk6YieXKtmCFksv6eTuxU34GiYtGxxWS/+yr8VOzZrUnsAZqSwkEHZpOsSY=
